# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = com.boxyplayz.backrooms
archives_name = boxys_backrooms
enabled_platforms = fabric

# Minecraft properties
minecraft_version = 26.1

# Dependencies
architectury_api_version = 20.0.12
fabric_loader_version = 0.19.5
fabric_api_version = 0.155.3+26.1.2
energy_reborn_version=5.0.0
forge_config_api_version=26.1.5
patchouli_version=26.1-94
