architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // Architectury API. This is optional, and you can comment it out if you don't need it.
    implementation "dev.architectury:architectury:$rootProject.architectury_api_version"

	runtimeOnly("fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:$forge_config_api_version")
	compileOnly("fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:$forge_config_api_version")

    runtimeOnly("com.fej1fun.potentials:potentials-common-26.1.2:$potentials_version")
    compileOnly("com.fej1fun.potentials:potentials-common-26.1.2:$potentials_version")
}

sourceSets {
    main {
        resources { // include generated resources in resources
            srcDir("src/generated/resources")
            exclude(".cache/**")
        }
    }
}