modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "boxys_backrooms"
version = "${version}"
displayName = "Boxy's Backrooms"
authors = "BoxyPlayz"
description = '''
Silly Backrooms Mod
'''
logoFile = "icon.png"
modUrl = "https://modrinth.com/mod/boxys-backrooms"
updateJSONURL = "https://boxyplayz.github.io/mods_updates/boxys_backrooms.json"
displayURL = "https://modrinth.com/mod/boxys-backrooms"

[[dependencies.boxys_backrooms]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.boxys_backrooms]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.boxys_backrooms]]
modId = "architectury"
type = "required"
versionRange = "[20.0.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.boxys_backrooms]]
modId = "patchouli"
type = "required"
versionRange = "[20.0.12,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "boxys_backrooms.mixins.json"
